name: Wdio test

on:
   workflow_dispatch:

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node Dependency
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          cd wdio
          npm install selenium-webdriver
          npm install wdio
          npm install

      - name: Run Test Case
        run: |
          cd wdio
          npm install
          npm run single
