name: Wdio test

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node Dependency
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0
      - run: |
          cd wdio
          npm install selenium-webdriver
          npm install webdriverio
          npm i

      - name: Run Test Case
        env:
          username: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}

        run: |
          cd wdio
          npm i
          cd tests
          cd specs
          npm run test

