name: Wdio test

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node Dependency
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd wdio
          npm install selenium-webdriver
          npm install webdriverio

      - name: Start LambdaTest Tunnel
        id: tunnel
        uses: ./ # Uses an action in the root directory
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"

      - name: Run Test Case
        env:
          username: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"

        run: |
          cd wdio
          cd tests
          cd specs

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
