name: Wdio test

on: push

jobs:
  test-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: |
          cd wdio
          npm install selenium-webdriver
          npm install webdriverio
          npm install # This installs other dependencies defined in your package.json

      - name: Start LambdaTest Tunnel
        id: tunnel
        uses: lambdatesttunnel/lambdatest-tunnel-action@v1
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"

      - name: Run Test Case
        env:
          username: ${{ secrets.LT_USERNAME }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "test tunnel"
        run: |
          cd wdio/tests/specs
          npm run single

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
