name: Wdio_2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the beginning of the hour

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    env:
      LT_USERNAME: "ritamg"
      LT_ACCESS_KEY: "unknown"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start LambdaTest Tunnel
      id: tunnel
      uses: ./ # Uses an action in the root directory
      with:
        user: "shubhamr"
        accessKey: "dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh"
        basicAuth: ${{ secrets.LT_BASIC_AUTH }}
        tunnelName: "test-tunnel-${{ github.run_number }}"
        verbose: true
    - run: |
        echo "Hello"
        cd wdio_2
        chmod +x ./node_modules/.bin/wdio
        npm install selenium-webdriver 
        npm install webdriverio
        npm i
        npm install
        npm run single
